### PR TITLE
Update of new agoTools features 

### PR DESCRIPTION
**Pull request by sam-berg**
Evan, these are some utilities that I added and have used.  PR for possible inclusion into esri-master per your review:

* Delete items listed in a CSV from an organization (deleteItems.py)
* Find items containing reference of specific path (findItemsContainingURL.py)
* Insert bookmarks into webmap from feature extents (populateBookmarks.py)
* Calculate status of attachments for features in layer (flagAttachments.py)

Samples for each.
All supporting code in admin class.

### CODE REVIEW

**Comment by ecaldwell** [comment]
Good stuff Sam. There's an existing PR (#36). The original issuer has gone dark, but his changes are worthwhile so I'd still like to pull them in. I'll try to evaluate which will be easier to merge last (yours or his). May take a bit of time, so stay tuned and thanks as always for the great contributions.

**Comment by ecaldwell** [comment]
No guts no glory. This stuff belongs in there. Now I just need to get that other PR cleaned up and merged in with this one.

**Comment by sam-berg** [comment]
Look out below!
Thanks, Evan...
Sam



On Fri, Jun 26, 2015 at 1:31 PM -0700, "Evan Caldwell" <notifications@github.com<mailto:notifications@github.com>> wrote:


No guts no glory. This stuff belongs in there. Now I just need to get that other PR cleaned up and merged in with this one.

**Comment by ecaldwell** [comment]
I spent a while in terminal testing merges and rebases between these two PRs. I had it just about sorted out when I realized Github was saying it could still automatically merge the second PR. I pulled the trigger and it all worked flawlessly. Color me impressed.

**Pull request merged**
